default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: 
  host: 127.0.0.1
  socket: /opt/homebrew/var/mysql/mysql.sock
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: course_enrollment_development

test:
  <<: *default
  database: course_enrollment_test

# production:
#   <<: *default
#   database: course_enrollment_production
#   username: course_enrollment
#   password: <%= ENV['COURSE_ENROLLMENT_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: course_enrollment_production
  username: root
  password: 1234